import type { Metadata } from "next";
import { Inter, Caveat } from "next/font/google";
import "./globals.css";

const caveat = Caveat({subsets: ["latin"]});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={caveat.className}>{children}</body>
    </html>
  );
}
